recursive: true
all: true
filename: "mock_{{ .InterfaceNameSnake }}.go"
mockname: "{{ .InterfaceName }}"
outpkg: "{{ base .PackageName }}mocks"
with-expecter: true
dir: "pkg/mocks/{{ .PackageName }}mocks"
packages:
  github.com/skiff-sh/pilot/pkg/protovalidatetype: { }
  github.com/skiff-sh/pilot/pkg/behavior/behaviortype: { }
  github.com/skiff-sh/pilot/pkg/httptype: { }
  github.com/skiff-sh/pilot/pkg/template: { }
  github.com/skiff-sh/pilot/api/go/pilot: { }
