// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: test/test.proto

package test

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Primitives with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Primitives) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Primitives with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PrimitivesMultiError, or
// nil if none found.
func (m *Primitives) ValidateAll() error {
	return m.validate(true)
}

func (m *Primitives) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for I32

	// no validation rules for I64

	// no validation rules for U32

	// no validation rules for U64

	// no validation rules for Str

	// no validation rules for Boolean

	// no validation rules for Dub

	// no validation rules for F32

	// no validation rules for Byt

	if m.I64Ptr != nil {
		// no validation rules for I64Ptr
	}

	if m.U32Ptr != nil {
		// no validation rules for U32Ptr
	}

	if m.U64Ptr != nil {
		// no validation rules for U64Ptr
	}

	if m.StrPtr != nil {
		// no validation rules for StrPtr
	}

	if m.BooleanPtr != nil {
		// no validation rules for BooleanPtr
	}

	if m.DubPtr != nil {
		// no validation rules for DubPtr
	}

	if m.F32Ptr != nil {
		// no validation rules for F32Ptr
	}

	if m.BytPtr != nil {
		// no validation rules for BytPtr
	}

	if m.I32Ptr != nil {
		// no validation rules for I32Ptr
	}

	if len(errors) > 0 {
		return PrimitivesMultiError(errors)
	}

	return nil
}

// PrimitivesMultiError is an error wrapping multiple validation errors
// returned by Primitives.ValidateAll() if the designated constraints aren't met.
type PrimitivesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrimitivesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrimitivesMultiError) AllErrors() []error { return m }

// PrimitivesValidationError is the validation error returned by
// Primitives.Validate if the designated constraints aren't met.
type PrimitivesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrimitivesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrimitivesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrimitivesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrimitivesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrimitivesValidationError) ErrorName() string { return "PrimitivesValidationError" }

// Error satisfies the builtin error interface
func (e PrimitivesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrimitives.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrimitivesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrimitivesValidationError{}
