name: Build and push image

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - Dockerfile

jobs:
  docker:
    name: Build and push
    uses: skiff-sh/gh-actions/.github/workflows/build-and-push.yml@master
    secrets: inherit
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      image-description: 'A generic server app that executes defined behavior.'
      push: true
      platforms: |
        linux/amd64
        linux/arm64
      images: |
        ghcr.io/${{ github.repository }}
      tags: |
        type=sha
        type=raw,value=latest
